---Editor UI highlight groups.
local M = {}

---Get editor UI highlight definitions.
---@param c table Colorscheme color table.
---@param hp table Helper functions/modules.
---@return table<string, table> highlights Editor UI highlight group definitions.
function M.get(c, hp)
	return {
		ColorColumn = { bg = c.base.dimmed5 },
		Conceal = { bg = c.editor.background, fg = c.base.dimmed3 },
		Cursor = { bg = c.base.foreground, fg = c.base.foreground },
		CursorColumn = { bg = c.editor.lineHighlightBackground },
		CursorLine = { bg = c.editor.lineHighlightBackground },
		CursorLineNr = { bg = c.editor.background, fg = c.base.green, bold = true },
		Directory = { bg = c.editorGroupHeader.tabsBackground, fg = c.statusBar.foreground },
		CursorLineFold = { bg = c.editor.background, fg = c.base.foreground },
		DiffAdd = { bg = c.diffEditor.insertedLineBackground, fg = c.diffEditorOverview.insertedForeground },
		DiffChange = { bg = c.diffEditor.modifiedLineBackground, fg = c.diffEditorOverview.modifiedForeground },
		DiffDelete = { bg = c.diffEditor.removedLineBackground, fg = c.diffEditorOverview.removedForeground },
		DiffText = { bg = c.editor.background, fg = c.editor.foreground },
		EndOfBuffer = { fg = c.editor.background },
		ErrorMsg = { bg = c.editor.background, fg = c.inputValidation.errorForeground },
		VertSplit = { bg = c.editor.background, fg = c.base.background },
		Folded = { bg = c.editor.foldBackground },
		FoldColumn = { bg = c.editor.background, fg = c.editorLineNumber.activeForeground },
		SignColumn = { bg = c.editor.background },
		LineNr = { bg = c.editor.background, fg = c.editorLineNumber.foreground },
		MatchParen = { fg = c.base.green, bold = true, underline = true },
		ModeMsg = { link = "Normal" },
		MsgArea = { link = "ModeMsg" },
		MsgSeparator = { link = "ModeMsg" },
		MoreMsg = { fg = c.base.yellow },
		NonText = { fg = c.editor.background },
		Normal = { bg = c.editor.background, fg = c.editor.foreground },
		NormalNC = { bg = c.editor.background, fg = c.editor.foreground },
		NormalFloat = { bg = c.base.overlay, fg = c.base.foreground },
		FloatBorder = { bg = c.base.overlay, fg = c.base.dimmed2 },
		FloatTitle = { bg = c.base.green, fg = c.base.background, bold = true },
		Pmenu = { bg = c.editorSuggestWidget.background, fg = c.editorSuggestWidget.foreground },
		PmenuSel = { bg = c.editorSuggestWidget.selectedBackground, bold = true },
		PmenuSbar = { bg = hp.lighten(c.editorSuggestWidget.background, -10) },
		PmenuThumb = { bg = c.scrollbarSlider.hoverBackground },
		Search = { bg = c.editor.findMatchHighlightBackground, fg = nil },
		IncSearch = { bg = c.base.yellow, fg = c.base.background, underline = false, bold = true },
		StatusLine = { bg = "NONE" },
		StatusLineNC = { bg = "NONE" },
		StatusLineSeparator = { fg = c.statusBar.background },
		StatusLineTerm = { fg = c.statusBar.background },
		StatusLineTermNC = { fg = c.statusBar.background },
		WinBar = { bg = "NONE" },
		WinBarNC = { bg = "NONE" },
		Tabline = { link = "BufferLineBackground" },
		TablineFill = { link = "BufferLineFill" },
		TablineSel = { link = "BufferLineBufferSelected" },
		Title = { fg = c.base.yellow, bold = true },
		Visual = { bg = c.base.dimmed4 },
		VisualNOS = { link = "Visual" },
		WarningMsg = { fg = c.inputValidation.warningForeground },
		WinSeparator = { fg = c.base.background },
		Whitespace = { fg = c.base.dimmed4 },
		diffAdded = { fg = c.base.green },
		diffChanged = { fg = c.base.yellow },
		diffRemoved = { fg = c.base.red },
		diffFile = { fg = c.base.yellow },
		diffNewFile = { fg = c.base.yellow },
		diffLine = { fg = c.base.blue },
		SpellBad = { fg = c.base.red, sp = c.base.red, undercurl = true },
		SpellCap = { fg = c.base.red, sp = c.base.red, undercurl = true },
		SpellLocal = { fg = c.base.red, sp = c.base.red, undercurl = true },
		SpellRare = { fg = c.base.red, sp = c.base.red, undercurl = true },
		healthError = { fg = c.base.red },
		healthSuccess = { fg = c.base.green },
		healthWarning = { fg = c.base.blue },
	}
end

return M
